Fashion/Areas/Admin/Controllers/AdvertisementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.EF;
using Model.DAO;

namespace Fashion.Areas.Admin.Controllers
{
    public class AdvertisementController : BaseController
    {
        //
        // GET: /Admin/Advertisement/
        public ActionResult Index()
        {
            return View(new AdvertisementDAO().ListAdvertisement());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(QuangCao _adv)
        {
            new AdvertisementDAO().CreateAdvertisement(_adv);
            return RedirectToAction("Index");
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            new AdvertisementDAO().DeleteAdvertisement(id);
            return RedirectToAction("Index");
        }
	}
}

Fashion/Areas/Admin/Views/Advertisement/Create.cshtml
@model Model.EF.QuangCao

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}
@section jsfooter
{
    <script>
        function BrowseServer() {
            var finder = new CKFinder();
            finder.selectActionFunction = SetFileField;
            finder.popup();
        }
        function SetFileField(fileUrl) {
            document.getElementById("Image").value = fileUrl;
        }
    </script>
}
<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon white edit"></i><span class="break"></span>Thêm quảng cáo</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>
        <div class="box-content">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="form-horizontal">
                    <fieldset>
                        <div class="control-group">
                            <label class="control-label" for="typeahead">Hình ảnh quảng cáo</label>
                            <div class="controls">
                                @Html.TextBoxFor(model => model.HinhAnhQC, new {@id = "Image", @name = "Image" })
                                <input value="Chọn ảnh" class="input-file uniform_on" id="fileInput" type="button" onclick="BrowseServer();" />
                            </div>
                        </div>

                        <div class="form-actions">
                            <a style="background-color:#702222; text-decoration: none; color: #fff" class="btn" href="@Url.Action("Index", "Advertisement")">Back to list</a>
                            <button type="submit" class="btn btn-primary" name="btnSubmit">Submit</button>
                            <button type="reset" class="btn">Reset</button>
                        </div>
                    </fieldset>
                </div>
            }


        </div>
    </div><!--/span-->
</div><!--/row-->

Fashion/Areas/Admin/Views/Advertisement/Index.cshtml
@model IEnumerable<Model.EF.QuangCao>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/Layout.cshtml";
}
<ul class="breadcrumb">
    <li>
        <i class="icon-home"></i>
        <a href="/Admin/Home">Trang chủ</a>
        <i class="icon-angle-right"></i>
    </li>
    <li><a href="#">Quảng cáo</a></li>
</ul>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2>Quảng cáo</h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon white wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon white chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon white remove"></i></a>
            </div>
        </div>

        <div class="box-content">

            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>
                            Hình ảnh
                        </th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr id="row_@item.MaQuangCao">
                            <td><img src="@item.HinhAnhQC" width="150px" /></td>
                            <td>
                                <a class="btn btn-danger" data-ajax="true" data-ajax-complete="$('#row_@item.MaQuangCao').remove()" data-ajax-confirm="Bạn có muốn xóa bản ghi này không?" data-ajax-method="Delete" href="/Admin/Advertisement/Delete/@item.MaQuangCao">
                                    <i class="halflings-icon white trash"></i> Xóa
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <a class="btn btn-success" href="@Url.Action("Create","Advertisement")">
                <i class="halflings-icon white zoom-in"></i>Thêm mới
            </a>
        </div>
    </div><!--/span-->
</div><!--/row-->